# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  usermanagementapi:
    image: usermanagementapi
    build:
      context: .
      dockerfile: UserManagement.API/Dockerfile
    ports:
      - 5193:5193
